feature: registration form 기능 추가
SWM-TEAM-GOYUKKURI/ToAnyone pull request #62
Opened 2022-10-13 14:45 UTC by ChoiEungi

### What I did
- Registration 폼을 채워넣을 수 있습니다. 
PUT `/user`
body는 swagger를 확인해주세요.

- LoginResponse에 `registrationFormFilled: boolean` 값이 전달됩니다. `/user`엔드포인트를 거치면 registrationFormFilled 값이 true로 변경됩니다.

Close #57 
Close #56

2022-10-13 15:22 UTC, somnisomni requested changes

2022-10-13 15:22 UTC, somnisomni commented on backend/src/main/java/anyone/to/soma/user/domain/type/Gender.java
> +    NON_BINARY,
프엔에서 `nonbinary`로 드린다고 했는데 이 코드 상으로는 `non_binary`로 드리도록 바꿔야될 것 같네요. 뭐 제가 다시 바꾸면 되죠...

2022-10-13 15:22 UTC, somnisomni commented on backend/src/main/java/anyone/to/soma/user/domain/type/Age.java
> +    FORTY,
오타입니다. `FORTY` -> `FOURTY`

2022-10-13 15:38 UTC, ChoiEungi commented on backend/src/main/java/anyone/to/soma/user/domain/type/Gender.java
> +    NON_BINARY,
제가 바꿔도 괜찮아요 필요하시면 dm주세요

2022-10-13 15:46 UTC, somnisomni commented on backend/src/main/java/anyone/to/soma/user/domain/type/Gender.java
> +    NON_BINARY,
아뇨 괜찮아요 아래꺼 수정하고 커밋해주세요

2022-10-14 04:50 UTC, ChoiEungi commented on backend/src/main/java/anyone/to/soma/user/domain/type/Age.java
> +    FORTY,
https://www.grammarly.com/blog/forty-fourty/

2022-10-14 07:14 UTC, somnisomni commented on backend/src/main/java/anyone/to/soma/user/domain/type/Age.java
> +    FORTY,
확인했습니다 제가 잘못배웠네요

2022-10-14 07:15 UTC, somnisomni approved these changes

2022-10-14 07:25 UTC, merged